# Generated by Django 6.0 on 2025-12-19 00:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='进货日期')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总金额')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已审核/执行'), ('cancelled', '已作废')], default='pending', max_length=20, verbose_name='状态')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.supplier', verbose_name='供应商')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, verbose_name='生产批号')),
                ('produce_date', models.DateField(verbose_name='生产日期')),
                ('expiry_date', models.DateField(verbose_name='有效期')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实际进价')),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='小计')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.medicine', verbose_name='药品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='biz.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReturnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='退货日期')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='退款总额')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已审核/执行'), ('cancelled', '已作废')], default='pending', max_length=20, verbose_name='状态')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.supplier', verbose_name='供应商')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReturnDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='退货单价')),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='小计')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.inventory', verbose_name='扣减库存')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='biz.purchasereturnorder')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='销售日期')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总金额')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已审核/执行'), ('cancelled', '已作废')], default='pending', max_length=20, verbose_name='状态')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer', verbose_name='客户')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='销售员')),
            ],
        ),
        migrations.CreateModel(
            name='SalesDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number_snapshot', models.CharField(blank=True, max_length=50, verbose_name='批号快照')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实际成交价')),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='小计')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.inventory', verbose_name='源库存')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='biz.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='退货日期')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='退款总额')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已审核/执行'), ('cancelled', '已作废')], default='pending', max_length=20, verbose_name='状态')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customer', verbose_name='退货客户')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturnDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('refund_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='退款单价')),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='小计')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.inventory', verbose_name='归还至库存')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='biz.salesreturnorder')),
            ],
        ),
    ]
