# Generated by Django 6.0 on 2025-12-26 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_medicine_idx_medicine_name_medicine_idx_manuf_price'),
        ('biz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasedetail',
            options={'verbose_name': '进货明细', 'verbose_name_plural': '进货明细'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-order_date'], 'verbose_name': '进货单', 'verbose_name_plural': '进货单'},
        ),
        migrations.AlterModelOptions(
            name='purchasereturndetail',
            options={'verbose_name': '采购退货明细', 'verbose_name_plural': '采购退货明细'},
        ),
        migrations.AlterModelOptions(
            name='purchasereturnorder',
            options={'ordering': ['-return_date'], 'verbose_name': '采购退货单', 'verbose_name_plural': '采购退货单'},
        ),
        migrations.AlterModelOptions(
            name='salesdetail',
            options={'verbose_name': '销售明细', 'verbose_name_plural': '销售明细'},
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-order_date'], 'verbose_name': '销售单', 'verbose_name_plural': '销售单'},
        ),
        migrations.AlterModelOptions(
            name='salesreturndetail',
            options={'verbose_name': '销售退货明细', 'verbose_name_plural': '销售退货明细'},
        ),
        migrations.AlterModelOptions(
            name='salesreturnorder',
            options={'ordering': ['-return_date'], 'verbose_name': '销售退货单', 'verbose_name_plural': '销售退货单'},
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='biz.purchaseorder', verbose_name='关联单据'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='小计'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实际进价'),
        ),
        migrations.AlterField(
            model_name='purchasereturndetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='biz.purchasereturnorder', verbose_name='关联单据'),
        ),
        migrations.AlterField(
            model_name='purchasereturndetail',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='purchasereturndetail',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='小计'),
        ),
        migrations.AlterField(
            model_name='purchasereturndetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='退货单价'),
        ),
        migrations.AlterField(
            model_name='salesdetail',
            name='actual_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实际成交价'),
        ),
        migrations.AlterField(
            model_name='salesdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='biz.salesorder', verbose_name='关联单据'),
        ),
        migrations.AlterField(
            model_name='salesdetail',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='salesdetail',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='小计'),
        ),
        migrations.AlterField(
            model_name='salesreturndetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='biz.salesreturnorder', verbose_name='关联单据'),
        ),
        migrations.AlterField(
            model_name='salesreturndetail',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='salesreturndetail',
            name='refund_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='退款单价'),
        ),
        migrations.AlterField(
            model_name='salesreturndetail',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='小计'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['order_date'], name='idx_purchase_date'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='idx_purchase_status'),
        ),
        migrations.AddIndex(
            model_name='purchasereturnorder',
            index=models.Index(fields=['return_date'], name='idx_purchasereturn_date'),
        ),
        migrations.AddIndex(
            model_name='purchasereturnorder',
            index=models.Index(fields=['status'], name='idx_purchasereturn_status'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['order_date'], name='idx_sales_date'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['status'], name='idx_sales_status'),
        ),
        migrations.AddIndex(
            model_name='salesreturnorder',
            index=models.Index(fields=['return_date'], name='idx_salesreturn_date'),
        ),
        migrations.AddIndex(
            model_name='salesreturnorder',
            index=models.Index(fields=['status'], name='idx_salesreturn_status'),
        ),
        migrations.AddConstraint(
            model_name='purchasedetail',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0), ('quantity__gte', 0)), name='check_purchase_price_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchasedetail',
            constraint=models.CheckConstraint(condition=models.Q(('expiry_date__gt', models.F('produce_date'))), name='check_expiry_after_produce'),
        ),
    ]
