# Generated by Django 6.0 on 2025-12-26 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0002_alter_purchasedetail_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='purchasereturnorder',
            new_name='idx_purchase_return_date',
            old_name='idx_purchasereturn_date',
        ),
        migrations.RenameIndex(
            model_name='purchasereturnorder',
            new_name='idx_purchase_return_status',
            old_name='idx_purchasereturn_status',
        ),
        migrations.RenameIndex(
            model_name='salesreturnorder',
            new_name='idx_sales_return_date',
            old_name='idx_salesreturn_date',
        ),
        migrations.RenameIndex(
            model_name='salesreturnorder',
            new_name='idx_sales_return_status',
            old_name='idx_salesreturn_status',
        ),
    ]
