# Generated by Django 6.0 on 2025-12-26 08:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_medicine_idx_medicine_name_medicine_idx_manuf_price'),
        ('biz', '0003_rename_idx_purchasereturn_date_idx_purchase_return_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', 'status'], name='idx_purch_sup_status'),
        ),
    ]
