# Generated by Django 6.0 on 2025-12-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(
                choices=[
                    ("manager", "经理 - 全权管理"),
                    ("purchaser", "采购员 - 进货管理"),
                    ("warehouse", "库管员 - 库存盘点"),
                    ("sales", "销售员 - 销售出库"),
                    ("finance", "财务 - 统计报表"),
                ],
                default="sales",
                max_length=20,
                verbose_name="职位",
            ),
        ),
    ]
