# Generated by Django 6.0 on 2025-12-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='employee',
            name='permission_level',
            field=models.IntegerField(default=1, help_text='1:普通, 5:管理, 9:系统', verbose_name='权限等级'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], default='M', max_length=10, verbose_name='性别'),
        ),
    ]
