# Generated by Django 6.0 on 2025-12-19 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50, verbose_name='省份')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('district', models.CharField(max_length=50, verbose_name='区县')),
                ('street', models.CharField(help_text='包含街道或乡镇信息', max_length=200, verbose_name='街道/乡镇')),
                ('detail_address', models.CharField(help_text='如:10号院3单元502室', max_length=200, verbose_name='详细地址')),
                ('zip_code', models.CharField(max_length=10, verbose_name='邮政编码')),
                ('name', models.CharField(max_length=100, verbose_name='客户姓名/药店名')),
                ('type', models.CharField(choices=[('wholesale', '批发'), ('retail', '零售')], max_length=20, verbose_name='类型')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100, verbose_name='通用名')),
                ('specification', models.CharField(max_length=50, verbose_name='规格')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='生产厂家')),
                ('approval_number', models.CharField(help_text='国药准字', max_length=50, unique=True, verbose_name='批准文号')),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='指导进价')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='指导售价')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50, verbose_name='省份')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('district', models.CharField(max_length=50, verbose_name='区县')),
                ('street', models.CharField(help_text='包含街道或乡镇信息', max_length=200, verbose_name='街道/乡镇')),
                ('detail_address', models.CharField(help_text='如:10号院3单元502室', max_length=200, verbose_name='详细地址')),
                ('zip_code', models.CharField(max_length=10, verbose_name='邮政编码')),
                ('name', models.CharField(max_length=100, verbose_name='供应商名称')),
                ('contact_person', models.CharField(max_length=50, verbose_name='联系人')),
                ('license_no', models.CharField(max_length=50, verbose_name='经营许可证号')),
                ('phone', models.CharField(help_text='多个电话用逗号分隔', max_length=50, verbose_name='联系电话')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, verbose_name='生产批号')),
                ('expiry_date', models.DateField(verbose_name='有效期至')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='当前数量')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.medicine', verbose_name='药品')),
            ],
            options={
                'verbose_name': '库存记录',
                'verbose_name_plural': '库存记录',
                'unique_together': {('medicine', 'batch_number')},
            },
        ),
    ]
