# Generated by Django 6.0 on 2025-12-26 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '客户', 'verbose_name_plural': '客户'},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name': '药品信息', 'verbose_name_plural': '药品信息'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': '供应商', 'verbose_name_plural': '供应商'},
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='phone',
        ),
        migrations.CreateModel(
            name='SupplierPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='电话号码')),
                ('type', models.CharField(choices=[('mobile', '手机'), ('office', '座机'), ('fax', '传真'), ('other', '其他')], default='mobile', max_length=10, verbose_name='类型')),
                ('note', models.CharField(blank=True, help_text='如：紧急联系人', max_length=50, verbose_name='备注')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='base.supplier', verbose_name='所属供应商')),
            ],
            options={
                'verbose_name': '联系电话',
                'verbose_name_plural': '联系电话',
            },
        ),
    ]
