# Generated by Django 6.0 on 2025-12-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_customer_options_alter_medicine_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['common_name'], name='idx_medicine_name'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['manufacturer', 'buy_price'], name='idx_manuf_price'),
        ),
    ]
